// packages/react-vtable/src/tables/base-table.tsx
/* eslint-disable react/display-name */
// import * as VTable from '@visactor/vtable';
// import { VTable } from '../vtable';
import React, { useState, useEffect, useRef, useImperativeHandle, useCallback } from 'react';
import type { ContainerProps } from '../containers/withContainer';
import withContainer from '../containers/withContainer';
import type { TableContextType } from '../context/table';
import RootTableContext from '../context/table';
import { isEqual, isNil, isNumber, pickWithout } from '@visactor/vutils';
import { toArray } from '../util';
import { REACT_PRIVATE_PROPS } from '../constants';
import type { IMarkElement } from '../table-components';
import type {
  EventsProps
  // LegendEventProps,
  // ScrollBarEventProps,
  // BrushEventProps,
  // DataZoomEventProps,
  // PlayerEventProps,
  // DimensionEventProps,
  // HierarchyEventProps,
  // TableLifeCycleEventProps
} from '../eventsUtils';
import { bindEventsToTable, TABLE_EVENTS_KEYS, TABLE_EVENTS } from '../eventsUtils';
import { VTableReactAttributePlugin } from '../table-components/custom/vtable-react-attribute-plugin';
import { reactEnvModule } from '../table-components/custom/vtable-browser-env-contribution';
import { container, isBrowserEnv } from '@visactor/vtable/es/vrender';
import type {
  ListTable,
  PivotTable,
  PivotChart,
  ListTableConstructorOptions,
  PivotTableConstructorOptions,
  PivotChartConstructorOptions
} from '@visactor/vtable';
import type { TYPES } from '@visactor/vtable';

export type IVTable = ListTable | PivotTable | PivotChart;
export type IOption = ListTableConstructorOptions | PivotTableConstructorOptions | PivotChartConstructorOptions;

export type BaseTableProps = EventsProps &
  IOption & {
    vtableConstrouctor?: any;
    type?: string;
    /** 上层container */
    container?: HTMLDivElement;
    /** option */
    option?: IOption;
    /** 数据 */
    records?: Record<string, unknown>[];
    /** 画布宽度 */
    width?: number | string;
    /** 画布高度 */
    height?: number | string;
    skipFunctionDiff?: boolean;
    keepColumnWidthChange?: boolean;

    ReactDOM?: any;

    reactAttributePlugin?: VTableReactAttributePlugin;

    /** 表格渲染完成事件 */
    onReady?: (instance: IVTable, isInitial: boolean) => void;
    /** throw error when chart run into an error */
    onError?: (err: Error) => void;
  };

// for react-vtable
if (isBrowserEnv()) {
  (container as any).load(reactEnvModule);
}

type Props = React.PropsWithChildren<BaseTableProps>;

const notOptionKeys = [
  ...REACT_PRIVATE_PROPS,
  ...TABLE_EVENTS_KEYS,
  'skipFunctionDiff',
  'onError',
  'onReady',
  'option',
  'records',
  'container',
  'vtableConstrouctor'
];

const getComponentId = (child: React.ReactNode, index: number) => {
  const componentName = child && (child as any).type && ((child as any).type.displayName || (child as any).type.name);
  return `${componentName}-${index}`;
};

const parseOptionFromChildren = (props: Props) => {
  const optionFromChildren: Omit<IOption, 'type' | 'data' | 'width' | 'height'> = {} as any;

  toArray(props.children).map((child, index) => {
    const parseOption = child && (child as any).type && (child as any).type.parseOption;

    if (parseOption && (child as any).props) {
      const childProps = isNil((child as any).props.componentId)
        ? {
            ...(child as any).props,
            componentId: getComponentId(child, index)
          }
        : (child as any).props;

      const optionResult = parseOption(childProps) as {
        optionName: keyof Omit<IOption, 'type' | 'data' | 'width' | 'height'>;
        isSingle: boolean;
        option: any;
      };

      if ((child as React.ReactElement).key) {
        optionResult.option.key = (child as React.ReactElement).key;
      }

      if (optionResult.isSingle) {
        optionFromChildren[optionResult.optionName] = optionResult.option as never;
      } else {
        if (!optionFromChildren[optionResult.optionName]) {
          optionFromChildren[optionResult.optionName] = [] as never;
        }

        optionFromChildren[optionResult.optionName].push(optionResult.option);
      }
    }
  });

  return optionFromChildren;
};

const BaseTable: React.FC<Props> = React.forwardRef((props, ref) => {
  const [updateId, setUpdateId] = useState<number>(0);
  const tableContext = useRef<TableContextType>({});
  useImperativeHandle(ref, () => tableContext.current?.table);
  const hasOption = !!props.option;
  const hasRecords = !!props.records;
  const isUnmount = useRef<boolean>(false);
  const prevOption = useRef(pickWithout(props, notOptionKeys));
  const optionFromChildren = useRef<Omit<IOption, 'records'>>(null);
  const prevRecords = useRef(props.records);
  const eventsBinded = React.useRef<BaseTableProps>(null);
  const skipFunctionDiff = !!props.skipFunctionDiff;
  const keepColumnWidthChange = !!props.keepColumnWidthChange;
  const columnWidths = useRef<Map<string, number>>(new Map());
  const pivotColumnWidths = useRef<{ dimensions: TYPES.IDimensionInfo[]; width: number }[]>([]);
  const pivotHeaderColumnWidths = useRef<number[]>([]);

  if (tableContext.current) {
    tableContext.current.onError = props.onError;
  }

  const parseOption = useCallback(
    (props: Props) => {
      if (hasOption && props.option) {
        if (hasRecords && props.records) {
          return {
            ...props.option,
            clearDOM: false,
            records: props.records
          };
        }
        return {
          ...props.option,
          clearDOM: false
        };
      }

      return {
        records: props.records,
        ...prevOption.current,
        ...optionFromChildren.current,
        clearDOM: false,
        customConfig: {
          ...prevOption.current.customConfig,
          createReactContainer: true
        }
        // ...tableContext.current?.optionFromChildren
      };
    },
    [hasOption, hasRecords]
  );

  const createTable = useCallback(
    (props: Props) => {
      const vtable = new props.vtableConstrouctor(props.container, parseOption(props));
      vtable.scenegraph.stage.reactAttribute = props.ReactDOM;
      vtable.scenegraph.stage.pluginService.register(props.reactAttributePlugin ?? new VTableReactAttributePlugin());
      vtable.scenegraph.stage.params.ReactDOM = props.ReactDOM;
      tableContext.current = { ...tableContext.current, table: vtable, onError: props.onError };
      isUnmount.current = false;

      columnWidths.current.clear();
      pivotColumnWidths.current = [];
      pivotHeaderColumnWidths.current = [];

      vtable.on('resize_column_end', (args: { col: number; colWidths: number[] }) => {
        const table = tableContext.current.table;
        if (!keepColumnWidthChange) {
          return;
        }
        const { col, colWidths } = args;
        const width = colWidths[col];
        if (vtable.isPivotTable()) {
          const path = (table as PivotTable).getCellHeaderPaths(col, table.columnHeaderLevelCount);
          let dimensions: TYPES.IDimensionInfo[];
          if (path.cellLocation === 'rowHeader') {
            dimensions = path.rowHeaderPaths as TYPES.IDimensionInfo[];
          } else {
            dimensions = path.colHeaderPaths as TYPES.IDimensionInfo[];
          }

          let found = false;
          pivotColumnWidths.current.forEach(item => {
            if (JSON.stringify(item.dimensions) === JSON.stringify(dimensions)) {
              item.width = width;
              found = true;
            }
          });
          if (!found) {
            pivotColumnWidths.current.push({ dimensions, width });
          }
        } else {
          const define = table.getBodyColumnDefine(col, 0);
          if ((define as any)?.key) {
            columnWidths.current.set((define as any).key, width);
          }
        }
      });
    },
    [parseOption]
  );

  const handleTableRender = useCallback(() => {
    if (!isUnmount.current) {
      if (!tableContext.current || !tableContext.current.table) {
        return;
      }
      // rebind events after render
      bindEventsToTable(tableContext.current.table, props, eventsBinded.current, TABLE_EVENTS);

      // to be fixed
      // will cause another useEffect
      setUpdateId(updateId + 1);
      if (props.onReady) {
        props.onReady(tableContext.current.table, updateId === 0);
      }
    }
  }, [updateId, setUpdateId, props]);

  const renderTable = useCallback(() => {
    if (tableContext.current.table) {
      // eslint-disable-next-line promise/catch-or-return
      tableContext.current.table.render();
      handleTableRender();
    }
  }, [handleTableRender]);

  useEffect(() => {
    const newOptionFromChildren = hasOption ? null : parseOptionFromChildren(props);

    if (!tableContext.current?.table) {
      if (!hasOption) {
        optionFromChildren.current = newOptionFromChildren;
      }

      createTable(props);
      renderTable();
      // bindEventsToTable(tableContext.current.table, props, null, TABLE_EVENTS);
      // tableContext.current = {
      //   ...tableContext.current,
      //   isChildrenUpdated: false
      // };
      eventsBinded.current = props;
      return;
    }

    if (hasOption) {
      if (!isEqual(eventsBinded.current.option, props.option, { skipFunction: skipFunctionDiff })) {
        const option = parseOption(props);
        if (keepColumnWidthChange) {
          const columnWidthConfig = updateWidthCache(
            columnWidths.current,
            pivotColumnWidths.current,
            tableContext.current.table
          );
          (option as any).columnWidthConfig = columnWidthConfig;
          (option as any).columnWidthConfigForRowHeader = columnWidthConfig;
        }
        // eslint-disable-next-line promise/catch-or-return
        tableContext.current.table.updateOption(option as any);
        handleTableRender();
        eventsBinded.current = props;
      } else if (
        hasRecords &&
        !isEqual(eventsBinded.current.records, props.records, { skipFunction: skipFunctionDiff })
      ) {
        if (keepColumnWidthChange) {
          const columnWidthConfig = updateWidthCache(
            columnWidths.current,
            pivotColumnWidths.current,
            tableContext.current.table
          );
          (tableContext.current.table.internalProps as any).columnWidthConfig = columnWidthConfig;
          (tableContext.current.table.internalProps as any).columnWidthConfigForRowHeader = columnWidthConfig;
        }
        tableContext.current.table.setRecords(props.records as any[]);
        handleTableRender();
        eventsBinded.current = props;
      }
      return;
    }

    const newOption = pickWithout(props, notOptionKeys);

    if (
      !isEqual(newOption, prevOption.current, { skipFunction: skipFunctionDiff }) ||
      // tableContext.current.isChildrenUpdated
      !isEqual(newOptionFromChildren, optionFromChildren.current, { skipFunction: skipFunctionDiff })
    ) {
      prevOption.current = newOption;
      optionFromChildren.current = newOptionFromChildren;

      const option = parseOption(props);
      if (keepColumnWidthChange) {
        const columnWidthConfig = updateWidthCache(
          columnWidths.current,
          pivotColumnWidths.current,
          tableContext.current.table
        );
        (option as any).columnWidthConfig = columnWidthConfig;
        (option as any).columnWidthConfigForRowHeader = columnWidthConfig;
      }
      tableContext.current.table.updateOption(option as any);

      // columnWidths.current = [];
      handleTableRender();
      eventsBinded.current = props;
    } else if (hasRecords && !isEqual(props.records, prevRecords.current, { skipFunction: skipFunctionDiff })) {
      prevRecords.current = props.records;

      if (keepColumnWidthChange) {
        const columnWidthConfig = updateWidthCache(
          columnWidths.current,
          pivotColumnWidths.current,
          tableContext.current.table
        );
        (tableContext.current.table.internalProps as any).columnWidthConfig = columnWidthConfig;
        (tableContext.current.table.internalProps as any).columnWidthConfigForRowHeader = columnWidthConfig;
      }

      tableContext.current.table.setRecords(props.records);
      handleTableRender();
      eventsBinded.current = props;
    }
    // tableContext.current = {
    //   ...tableContext.current,
    //   isChildrenUpdated: false
    // };
  }, [createTable, hasOption, hasRecords, parseOption, handleTableRender, renderTable, skipFunctionDiff, props]);

  useEffect(() => {
    return () => {
      if (tableContext) {
        if (tableContext.current && tableContext.current.table) {
          tableContext.current.table.release();
          tableContext.current = null;
        }
      }
      eventsBinded.current = null;
      isUnmount.current = true;
    };
  }, []);

  return (
    <RootTableContext.Provider value={tableContext.current}>
      {toArray(props.children).map((child: React.ReactNode, index: number) => {
        if (typeof child === 'string') {
          return null;
        }

        const childId = getComponentId(child, index);

        // const componentName =
        //   child && (child as any).type && ((child as any).type.displayName || (child as any).type.name);
        // const childId = `${componentName}-${index}`;

        return (
          // <React.Fragment key={(child as any)?.props?.id ?? (child as any)?.id ?? `child-${index}`}>
          //   {React.cloneElement(child as IMarkElement, {
          //     updateId: updateId
          //   })}
          // </React.Fragment>
          <React.Fragment key={childId}>
            {React.cloneElement(child as React.ReactElement<any, React.JSXElementConstructor<any>>, {
              updateId: updateId,
              componentId: childId,
              componentIndex: index
            })}
          </React.Fragment>
        );
      })}
    </RootTableContext.Provider>
  );
});

export const createTable = <T extends Props>(
  componentName: string,
  defaultProps?: Partial<T>,
  callback?: (props: T) => T
) => {
  const Com = withContainer<ContainerProps, T>(BaseTable as any, componentName, (props: T) => {
    // props.type = type;

    if (defaultProps) {
      return Object.assign(props, defaultProps);
    }

    // if (callback) {
    //   return callback(props);
    // }

    // if (type) {
    //   return { ...props, type };
    // }
    return props;
  });
  Com.displayName = componentName;
  return Com;
};

function updateWidthCache(
  columnWidths: Map<string, number>,
  pivotColumnWidths: { dimensions: TYPES.IDimensionInfo[]; width: number }[],
  table: IVTable
) {
  if (table.isPivotTable()) {
    return pivotColumnWidths;
  }
  const columnWidthConfig: { key: string; width: number }[] = [];
  columnWidths.forEach((width, key) => {
    columnWidthConfig.push({
      key,
      width
    });
  });
  return columnWidthConfig;
}

// packages/vue-vtable/src/tables/base-table.vue
<template>
  <div ref="vTableContainer" :style="{ width: containerWidth, height: containerHeight }" style="position: relative" />
</template>

<script setup lang="ts">
import { ref, shallowRef, watch, computed, onMounted, onBeforeUnmount } from 'vue';
import { ListTable, PivotTable, PivotChart } from '@visactor/vtable';
import { isEqual, isValid } from '@visactor/vutils';
import { TABLE_EVENTS, TABLE_EVENTS_KEYS } from '../eventsUtils';
import type * as VTable from '@visactor/vtable';
import type { EventsProps } from '../eventsUtils';
import type { TYPES } from '@visactor/vtable';
import { VTableVueAttributePlugin } from '../components/custom/vtable-vue-attribute-plugin';
import { releaseRenderEditor, resolveRenderEditor } from '../edit';

// 定义表格实例和选项的类型
export type IVTable = VTable.ListTable | VTable.PivotTable | VTable.PivotChart;
export type IOption =
  | VTable.ListTableConstructorOptions
  | VTable.PivotTableConstructorOptions
  | VTable.PivotChartConstructorOptions;

// 定义组件的属性接口
export interface BaseTableProps extends EventsProps {
  type?: string;
  options?: IOption;
  records?: Record<string, unknown>[];
  width?: number | string;
  height?: number | string;
  onReady?: (instance: IVTable, isInitial: boolean) => void;
  onError?: (err: Error) => void;
  keepColumnWidthChange?: boolean;
}

// 设置默认属性
const props = withDefaults(defineProps<BaseTableProps>(), {
  width: '100%',
  height: '100%'
});

// 创建用于引用 DOM 元素和表格实例的 ref
const vTableContainer = ref<HTMLElement | null>(null);
const vTableInstance = shallowRef<IVTable | null>(null);

// for keepColumnWidthChange
const columnWidths = ref<Map<string, number>>(new Map());
const pivotColumnWidths = ref<{ dimensions: TYPES.IDimensionInfo[]; width: number }[]>([]);
const pivotHeaderColumnWidths = ref<number[]>([]);

// 公开 vTableInstance，以便外部组件可以访问
defineExpose({ vTableInstance });

// 计算容器的宽度和高度
const containerWidth = computed(() => (typeof props.width === 'number' ? `${props.width}px` : props.width));
const containerHeight = computed(() => (typeof props.height === 'number' ? `${props.height}px` : props.height));

// 绑定事件到表格实例
const emit = defineEmits(TABLE_EVENTS_KEYS);
const bindEvents = (instance: IVTable) => {
  TABLE_EVENTS_KEYS.forEach(eventKey => {
    const vueEventHandler = (event: any) => {
      emit(eventKey, event);
    };
    instance.on(TABLE_EVENTS[eventKey as keyof typeof TABLE_EVENTS], vueEventHandler);
  });
};

type Constructor<T> = new (dom: HTMLElement, options: IOption) => T;

// 创建表格实例
// use Constructor<T> will cause error in rollup-plugin-typescript2, use any temporarily
const createTableInstance = (Type: any, options: IOption) => {
  const vtable = new Type(vTableContainer.value!, options);
  vTableInstance.value = vtable;
  // 注册 vtable-vue 自定义组件集成插件
  vtable.scenegraph.stage.pluginService.register(new VTableVueAttributePlugin());
  // 校验并植入渲染式编辑器
  resolveRenderEditor(vtable, options);

  // for keepColumnWidthChange
  columnWidths.value.clear();
  pivotColumnWidths.value = [];
  pivotHeaderColumnWidths.value = [];

  vtable.on('resize_column_end', (args: { col: number; colWidths: number[] }) => {
    // const table = vTableInstance.value;
    if (!props.keepColumnWidthChange) {
      return;
    }
    const { col, colWidths } = args;
    const width = colWidths[col];
    if (vtable.isPivotTable()) {
      const path = (vtable as PivotTable).getCellHeaderPaths(col, vtable.columnHeaderLevelCount);
      let dimensions = null;
      if (path.cellLocation === 'rowHeader') {
        dimensions = path.rowHeaderPaths as TYPES.IDimensionInfo[];
      } else {
        dimensions = path.colHeaderPaths as TYPES.IDimensionInfo[];
      }

      let found = false;
      // pivotColumnWidths.value.forEach(item => {
      //   if (JSON.stringify(item.dimensions) === JSON.stringify(dimensions)) {
      //     item.width = width;
      //     found = true;
      //   }
      // });
      for (let i = 0; i < pivotColumnWidths.value.length; i++) {
        const item = pivotColumnWidths.value[i];
        if (JSON.stringify(item.dimensions) === JSON.stringify(dimensions)) {
          item.width = width;
          found = true;
        }
      }
      if (!found) {
        pivotColumnWidths.value.push({ dimensions, width });
      }
    } else {
      const define = vtable.getBodyColumnDefine(col, 0);
      if ((define as any)?.key) {
        columnWidths.value.set((define as any).key, width);
      }
    }
  });
};

const createVTable = () => {
  if (!vTableContainer.value) {
    return;
  }

  if (vTableInstance.value) {
    vTableInstance.value.release();
  }

  const getRecords = () => {
    return props.records !== undefined && props.records !== null && props.records.length > 0
      ? props.records
      : props.options.records;
  };

  try {
    switch (props.type) {
      case 'list':
        createTableInstance(ListTable, {
          ...props.options,
          records: getRecords()
        } as VTable.ListTableConstructorOptions);
        break;
      case 'pivot':
        createTableInstance(PivotTable, {
          ...props.options,
          records: getRecords()
        } as VTable.PivotTableConstructorOptions);
        break;
      case 'chart':
        createTableInstance(PivotChart, {
          ...props.options,
          records: getRecords()
        } as VTable.PivotChartConstructorOptions);
        break;
    }
    bindEvents(vTableInstance.value);
    props.onReady?.(vTableInstance.value, true);
  } catch (err) {
    console.error('Error creating table instance:', err);
    props.onError?.(err as Error);
  }
};

// 更新表格实例
const updateVTable = (newOptions: IOption) => {
  if (!vTableInstance.value) {
    return;
  }

  try {
    // for keepColumnWidthChange, update column width

    if (props.keepColumnWidthChange) {
      const columnWidthConfig = updateWidthCache(columnWidths.value, pivotColumnWidths.value, vTableInstance.value);
      newOptions = {
        ...newOptions,
        columnWidthConfig: columnWidthConfig as any,
        columnWidthConfigForRowHeader: columnWidthConfig as any
      };
    }
    switch (props.type) {
      case 'list':
        if (vTableInstance.value instanceof ListTable) {
          vTableInstance.value.updateOption(newOptions as VTable.ListTableConstructorOptions);
        }
        break;
      case 'pivot':
        if (vTableInstance.value instanceof PivotTable) {
          vTableInstance.value.updateOption(newOptions as VTable.PivotTableConstructorOptions);
        }
        break;
      case 'chart':
        if (vTableInstance.value instanceof PivotChart) {
          vTableInstance.value.updateOption(newOptions as VTable.PivotChartConstructorOptions);
        }
        break;
    }
  } catch (err) {
    props.onError?.(err as Error);
  }
};

// 组件挂载时创建表格
onMounted(createVTable);
onBeforeUnmount(() => {
  vTableInstance.value?.release();
  const { id } = vTableInstance.value || {};
  if (isValid(id)) {
    // 移除自定义编辑器
    releaseRenderEditor(id);
  }
});

// 监听 options 属性的变化
// 需要去做细颗粒度的比较
// deep 选中会导致tree失效
watch(
  () => props.options,
  (newOptions, oldOptions) => {
    if (vTableInstance.value) {
      updateVTable(newOptions);
      if (!isEqual(newOptions.columns, oldOptions?.columns)) {
        // 更新编辑列
        resolveRenderEditor(vTableInstance.value, newOptions);
      }
    } else {
      createVTable();
    }
  }
  // { deep: true },
);

// 监听 records 属性的变化并更新表格
// 需要去做细颗粒度的比较
watch(
  () => props.records,
  (newRecords, oldRecords) => {
    // if (!isEqual(newRecords, oldRecords)) {
    if (vTableInstance.value) {
      updateVTable({ ...props.options, records: newRecords });
    } else {
      createVTable();
    }
    // }
  },
  { deep: true }
);

function updateWidthCache(
  columnWidths: Map<string, number>,
  pivotColumnWidths: { dimensions: TYPES.IDimensionInfo[]; width: number }[],
  table: IVTable
) {
  if (table.isPivotTable()) {
    return pivotColumnWidths;
  }
  const columnWidthConfig: { key: string; width: number }[] = [];
  columnWidths.forEach((width, key) => {
    columnWidthConfig.push({
      key,
      width
    });
  });
  return columnWidthConfig;
}
</script>
